### ISSUE TITLE
Identity graph générable à partir du Versions graph

### ISSUE THREAD

**Issue by JLCochardSFA** [bfh/version-link#13]
Dans l'exemple des communes, cela n'est pas vrai car l'indication de numéro de commune de l'OFS qui sert à construire les entités de l'Identity Graph n'existe nulle part dans le Versions graphs.
Pour que ce mécanisme de génération puisse avoir lieu, il faudrait que le numéro OFS soit un attribut des versions du Versions graph.
Ainsi on arrive à imaginer le processus de création du Identity Graph

**Comment by bequrios** [comment]
Danke, vl:identityIdentifier hat noch gefehlt im Beispiel und ist jetzt angefügt.
