### ISSUE TITLE
The use of the profile predicates in the docu is confusing

### ISSUE THREAD

**Issue by l00mi** [bfh/version-link#14]
The use of vl:*Predicate as below is confusing. It suggest to use this directly as predicate. 

<img width="451" alt="Screenshot 2022-12-07 at 22 14 24" src="https://user-images.githubusercontent.com/502518/206297876-956b5b35-1438-4520-9939-58d110f4553e.png">

Either we need to introduce a special syntax form here. Probably better to just use one profile (e.g. the schema.org profile) and then explain it in detail.

**Comment by bequrios** [comment]
changed in the docu so that the predicates of the schema.org profile are used
